{'bearer_token':'AAAAAAAAAAAAAAAAAAAAAMaVQAEAAAAARPu29tOALH43UWMoGrv44jv9NrM%3DANVoVAIz7af1oC9XiZaTgqsYwNBVnmDYQXkL0KMd3IOtZGcEDI',
'api_key':'qFOfjvUsXOQszfIofyDgWm8jc',
'api_secret_key':'otWyX6n1kbTYcmn3bxlPWKXAxqjY3cdJHpmhwcVE1N2ZYxP7F7',
'access_token':'4824693621-ZVSaw4l30hHtiSo2gYvYVyO12pZAnVitkuZAye3',
'access_token_secret':'a47xSaH7hLR0bbWfE86DdoOJYRE6S3GX2hIgOsQzYQzb5'
}